// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKIPkd37zthtLB1qfmp9T16GIE6z_PE4k',
    appId: '1:146247947663:web:3495a0178898978b2167fa',
    messagingSenderId: '146247947663',
    projectId: 'shop-db29e',
    authDomain: 'shop-db29e.firebaseapp.com',
    databaseURL: 'https://shop-db29e.firebaseio.com',
    storageBucket: 'shop-db29e.appspot.com',
    measurementId: 'G-0V26HS34P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3EaQ-GoaBQs7nhxCuYLP5sYRL-Brc_Ow',
    appId: '1:146247947663:android:6100d30b2db9e4c42167fa',
    messagingSenderId: '146247947663',
    projectId: 'shop-db29e',
    databaseURL: 'https://shop-db29e.firebaseio.com',
    storageBucket: 'shop-db29e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2l1Yq5uhNJRkwRNqxFOtmWmrytojFyo',
    appId: '1:146247947663:ios:b170fefd1320207e2167fa',
    messagingSenderId: '146247947663',
    projectId: 'shop-db29e',
    databaseURL: 'https://shop-db29e.firebaseio.com',
    storageBucket: 'shop-db29e.appspot.com',
    androidClientId: '146247947663-lg3hf2b0ffnn9dpbm4l3cb8pi6g1ncfo.apps.googleusercontent.com',
    iosClientId: '146247947663-fhsf6oc93kuv789j86dmd31ga28ja0e1.apps.googleusercontent.com',
    iosBundleId: 'com.salamshop.salamshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2l1Yq5uhNJRkwRNqxFOtmWmrytojFyo',
    appId: '1:146247947663:ios:b170fefd1320207e2167fa',
    messagingSenderId: '146247947663',
    projectId: 'shop-db29e',
    databaseURL: 'https://shop-db29e.firebaseio.com',
    storageBucket: 'shop-db29e.appspot.com',
    androidClientId: '146247947663-lg3hf2b0ffnn9dpbm4l3cb8pi6g1ncfo.apps.googleusercontent.com',
    iosClientId: '146247947663-fhsf6oc93kuv789j86dmd31ga28ja0e1.apps.googleusercontent.com',
    iosBundleId: 'com.salamshop.salamshop',
  );
}
